/** Default forum categories for create-post when DB has none. */
export const DEFAULT_FORUM_CATEGORIES = [
  {
    id: 'pregnancy-journey',
    name: 'Pregnancy Journey',
    description: 'Share your pregnancy experiences',
    slug: 'pregnancy-journey',
    color: '#FF6B6B',
    icon: 'pregnancy',
    order: 1,
    isActive: true,
  },
  {
    id: 'first-trimester',
    name: 'First Trimester',
    description: 'Early pregnancy (weeks 1-12)',
    slug: 'first-trimester',
    color: '#FF9F43',
    icon: 'baby-bump',
    order: 2,
    isActive: true,
  },
  {
    id: 'second-trimester',
    name: 'Second Trimester',
    description: 'Mid-pregnancy topics',
    slug: 'second-trimester',
    color: '#10AC84',
    icon: 'baby-heartbeat',
    order: 3,
    isActive: true,
  },
  {
    id: 'third-trimester',
    name: 'Third Trimester',
    description: 'Late pregnancy and labor',
    slug: 'third-trimester',
    color: '#0ABDE3',
    icon: 'baby-carriage',
    order: 4,
    isActive: true,
  },
  {
    id: 'newborn-care',
    name: 'Newborn Care',
    description: 'Caring for your newborn',
    slug: 'newborn-care',
    color: '#54A0FF',
    icon: 'baby-bottle',
    order: 5,
    isActive: true,
  },
  {
    id: 'nutrition-diet',
    name: 'Nutrition & Diet',
    description: 'Healthy eating',
    slug: 'nutrition-diet',
    color: '#00D2D3',
    icon: 'nutrition',
    order: 6,
    isActive: true,
  },
  {
    id: 'mental-health',
    name: 'Mental Health',
    description: 'Emotional wellbeing',
    slug: 'mental-health',
    color: '#FF6B9D',
    icon: 'mental-health',
    order: 7,
    isActive: true,
  },
  {
    id: 'community-support',
    name: 'Community Support',
    description: 'General support',
    slug: 'community-support',
    color: '#FF6B9D',
    icon: 'community',
    order: 8,
    isActive: true,
  },
];
