import { CommonModule, NgOptimizedImage } from '@angular/common';
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { RouterLink, RouterModule, RouterOutlet } from '@angular/router';
import {
  IonApp,
  IonAvatar,
  IonBackButton,
  IonButton,
  IonButtons,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonContent,
  IonDatetime,
  IonFooter,
  IonHeader,
  IonIcon,
  IonInput,
  IonInputOtp,
  IonItem,
  IonItemDivider,
  IonLabel,
  IonList,
  IonMenu,
  IonMenuButton,
  IonModal,
  IonNav,
  IonNavLink,
  IonPicker,
  IonPickerColumn,
  IonPickerColumnOption,
  IonRouterLink,
  IonRouterOutlet,
  IonSegment,
  IonSegmentButton,
  IonTab,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonText,
  IonTitle,
  IonToast,
  IonToggle,
  IonToolbar,
  IonRadio,
  IonRadioGroup,
  IonNote,
  IonSelect,
  IonSelectOption,
  IonDatetimeButton,
  IonSearchbar,
  IonSpinner,
} from '@ionic/angular/standalone';
import { CircleProgressBarComponent } from './components/circle-progress-bar/circle-progress-bar.component';
import { SearchModalComponent } from './components/search-modal/search-modal.component';
import { MapboxMapComponent } from './components/mapbox-map/mapbox-map.component';
import { MapService } from './services/map.service';

const IONIC_MODULES = [
  IonInput,
  IonDatetimeButton,
  IonItem,
  IonList,
  IonInputOtp,
  IonToggle,
  IonButton,
  IonFooter,
  IonToast,
  IonContent,
  IonHeader,
  IonIcon,
  IonTab,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonTitle,
  IonToolbar,
  IonLabel,
  IonBackButton,
  IonButtons,
  IonMenuButton,
  IonToolbar,
  IonMenu,
  IonAvatar,
  IonItemDivider,
  IonNavLink,
  IonNav,
  IonRouterLink,
  IonSegment,
  IonSegmentButton,
  IonApp,
  IonModal,
  IonDatetime,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonText,
  IonPicker,
  IonPickerColumn,
  IonPickerColumnOption,
  IonRadio,
  IonRadioGroup,
  IonNote,
  IonSelect,
  IonSelectOption,
  IonSearchbar,
  IonSpinner,
];

const COMMON_MODULES = [
  CommonModule,
  ReactiveFormsModule,
  FormsModule,
  NgOptimizedImage,
  RouterLink,
  RouterOutlet,
  RouterModule,
  IonRouterOutlet,
  HttpClientModule,
];

@NgModule({
  declarations: [CircleProgressBarComponent, SearchModalComponent, MapboxMapComponent],
  imports: [...COMMON_MODULES, ...IONIC_MODULES, RouterModule.forChild([])],
  exports: [...COMMON_MODULES, ...IONIC_MODULES, CircleProgressBarComponent, SearchModalComponent, MapboxMapComponent],
  providers: [MapService],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class SharedModule {}
