import { CommonModule, NgOptimizedImage } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterLink, RouterModule, RouterOutlet } from '@angular/router';
import {
  IonApp,
  IonAvatar,
  IonBackButton,
  IonButton,
  IonButtons,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonContent,
  IonDatetime,
  IonFooter,
  IonHeader,
  IonIcon,
  IonInput,
  IonInputOtp,
  IonItem,
  IonItemDivider,
  IonLabel,
  IonList,
  IonMenu,
  IonMenuButton,
  IonModal,
  IonNav,
  IonNavLink,
  IonPicker,
  IonPickerColumn,
  IonPickerColumnOption,
  IonRouterLink,
  IonRouterOutlet,
  IonSegment,
  IonSegmentButton,
  IonTab,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonText,
  IonTitle,
  IonToast,
  IonToggle,
  IonToolbar,
  IonRadio,
  IonRadioGroup,
  IonNote
} from '@ionic/angular/standalone';
import { CircleProgressBarComponent } from './components/circle-progress-bar/circle-progress-bar.component';

const IONIC_MODULES = [
  IonInput,
  IonItem,
  IonList,
  IonInputOtp,
  IonToggle,
  IonButton,
  IonFooter,
  IonToast,
  IonContent,
  IonHeader,
  IonIcon,
  IonTab,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonTitle,
  IonToolbar,
  IonLabel,
  IonBackButton,
  IonButtons,
  IonMenuButton,
  IonToolbar,
  IonMenu,
  IonAvatar,
  IonItemDivider,
  IonNavLink,
  IonNav,
  IonRouterLink,
  IonSegment,
  IonSegmentButton,
  IonApp,
  IonModal,
  IonDatetime,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonText,
  IonPicker,
  IonPickerColumn,
  IonPickerColumnOption,
  IonRadio,
  IonRadioGroup,
  IonNote,
  
];

const COMMON_MODULES = [
  CommonModule,
  ReactiveFormsModule,
  FormsModule,
  NgOptimizedImage,
  RouterLink,
  RouterOutlet,
  RouterModule,
  IonRouterOutlet,
];

@NgModule({
  declarations: [CircleProgressBarComponent,

  ],
  imports: [...COMMON_MODULES, ...IONIC_MODULES, RouterModule.forChild([])],
  exports: [...COMMON_MODULES, ...IONIC_MODULES, CircleProgressBarComponent],
  providers: [],
})
export class SharedModule {}
