import { CommonModule, NgOptimizedImage } from '@angular/common';
import { RouterLink, RouterOutlet } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import {
  IonApp,
  IonAvatar,
  IonBackButton,
  IonBadge,
  IonButton,
  IonButtons,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonContent,
  IonDatetime,
  IonDatetimeButton,
  IonFab,
  IonFabButton,
  IonFooter,
  IonHeader,
  IonIcon,
  IonInput,
  IonInputOtp,
  IonItem,
  IonItemDivider,
  IonLabel,
  IonList,
  IonMenu,
  IonMenuButton,
  IonMenuToggle,
  IonModal,
  IonNav,
  IonNavLink,
  IonNote,
  IonPicker,
  IonPickerColumn,
  IonPickerColumnOption,
  IonRadio,
  IonRadioGroup,
  IonRange,
  IonRefresher,
  IonRefresherContent,
  IonRouterLink,
  IonRouterOutlet,
  IonSearchbar,
  IonSegment,
  IonSegmentButton,
  IonSelect,
  IonSelectOption,
  IonSpinner,
  IonTab,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonText,
  IonTextarea,
  IonToggle,
  IonTitle,
  IonToolbar,
  IonToast,
  IonChip
} from '@ionic/angular/standalone';

import { TranslatePipe } from './pipes/translate.pipe';
import { LanguageSwitcherComponent } from './components/language-switcher/language-switcher.component';
import { HeaderLanguageSwitcherComponent } from './components/header-language-switcher/header-language-switcher.component';
import { CircleProgressBarComponent } from './components/circle-progress-bar/circle-progress-bar.component';
import { MapboxMapComponent } from './components/mapbox-map/mapbox-map.component';
/**
 * Drop-in replacement for the old `SharedModule`.
 * Use this in `standalone` component `imports` arrays.
 */
export const SHARED_STANDALONE_IMPORTS = [
  CommonModule,
  FormsModule,
  ReactiveFormsModule,
  NgOptimizedImage,
  RouterLink,
  RouterOutlet,
  IonRouterOutlet,

  // Ionic standalone components (mirrors the old SharedModule exports)
  IonInput,
  IonDatetimeButton,
  IonItem,
  IonList,
  IonInputOtp,
  IonToggle,
  IonButton,
  IonBadge,
  IonFab,
  IonFabButton,
  IonFooter,
  IonToast,
  IonContent,
  IonHeader,
  IonIcon,
  IonChip,
  IonTab,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonTitle,
  IonLabel,
  IonBackButton,
  IonButtons,
  IonMenuButton,
  IonToolbar,
  IonMenu,
  IonAvatar,
  IonItemDivider,
  IonNavLink,
  IonNav,
  IonRouterLink,
  IonSegment,
  IonSegmentButton,
  IonApp,
  IonModal,
  IonDatetime,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonText,
  IonPicker,
  IonPickerColumn,
  IonPickerColumnOption,
  IonRadio,
  IonRadioGroup,
  IonNote,
  IonRefresher,
  IonRefresherContent,
  IonRange,
  IonSelect,
  IonSelectOption,
  IonSearchbar,
  IonSpinner,
  IonMenuToggle,
  IonTextarea,

  TranslatePipe,
  LanguageSwitcherComponent,
  HeaderLanguageSwitcherComponent,
  CircleProgressBarComponent,
  MapboxMapComponent,
] as const;

