### Create a new forum thread
POST http://localhost:3000/api/v1/forum-threads
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE

{
  "title": "First title for pregnancy",
  "description": "First content for pregnancy",
  "categoryId": "f0b9c533-443e-464a-95ef-7dab41aa5886",
  "tags": ["cramps"]
}

### Get all forum threads
GET http://localhost:3000/api/v1/forum-threads

### Get threads by category
GET http://localhost:3000/api/v1/forum-threads?categoryId=f0b9c533-443e-464a-95ef-7dab41aa5886
