/** Privacy Policy copy for settings /privacy-policy (## = section heading, one paragraph per line). */
export const PRIVACY_POLICY = {
  en: {
    effectiveDate: 'Last updated: June 1, 2026',
    body: [
      'This Privacy Policy explains how NouraCare ("we," "us," or "our") collects, uses, stores, and shares information when you use the NouraCare mobile application, website, and related services (the "Service"). By using the Service, you agree to the practices described here. If you do not agree, please do not use the Service.',
      '## 1. Who We Are',
      'NouraCare provides digital tools for menstrual cycle, fertility, pregnancy, and related wellness tracking. For privacy questions or requests, contact us at support@nouracare.app.',
      '## 2. Information We Collect',
      'We collect information in these categories: (a) Account information — such as name, email address, phone number (if provided), profile photo, and authentication identifiers from sign-in providers; (b) Health and wellness data you enter — including cycle dates, symptoms, moods, notes, pregnancy information, fertility logs, and reminders; (c) Device and app data — such as device type, operating system, app version, language, and general diagnostic logs; (d) Usage data — such as features used, interaction events, and crash reports; (e) Communications — support messages, feedback, and community posts you choose to submit; (f) Optional analytics — if you enable anonymized data sharing in Settings, we may collect aggregated or de-identified usage statistics to improve the Service.',
      '## 3. How We Use Information',
      'We use information to: provide and personalize the Service (including predictions and reminders); sync your data across devices when you sign in; operate community, consultation, and educational features; send notifications you request; maintain security and prevent abuse; analyze performance and fix bugs; comply with legal obligations; and, with your consent where required, improve the Service through optional analytics.',
      '## 4. Legal Bases for Processing',
      'Depending on your location, we process personal data based on: performance of our contract with you (providing the Service); your consent (for example, optional analytics or certain notifications); our legitimate interests (security, product improvement, and support) balanced against your rights; and compliance with legal obligations.',
      '## 5. How We Share Information',
      'We do not sell your personal health information. We may share information: (a) with service providers who help us host, store, analyze, email, or support the Service under confidentiality obligations; (b) with health professionals or platforms you choose to connect with through optional consultation features, according to your actions; (c) when required by law, regulation, legal process, or to protect rights, safety, and security; (d) in connection with a merger, acquisition, or asset sale, subject to continued protection; or (e) with your explicit direction or consent. Aggregated or de-identified data that cannot reasonably identify you may be used for analytics and reporting.',
      '## 6. Sensitive Health Data',
      'Health information you log in NouraCare is treated as sensitive. We apply additional safeguards such as access controls and encryption in transit. You control what you enter, and you can use privacy settings (including hiding sensitive notification content on your lock screen) to reduce exposure on your device.',
      '## 7. Your Choices and Rights',
      'Depending on applicable law, you may have the right to access, correct, export, restrict, or delete your personal data; withdraw consent where processing is consent-based; and object to certain processing. You can export data or request account deletion from Settings. You may disable optional anonymized data sharing in Settings. To exercise rights, contact support@nouracare.app. We may need to verify your identity before responding.',
      '## 8. Data Retention',
      'We retain information for as long as your account is active or as needed to provide the Service, resolve disputes, enforce agreements, and comply with law. When you delete your account, we delete or anonymize personal data within a reasonable period, except where retention is required for legal, security, or backup purposes.',
      '## 9. Security',
      'We use administrative, technical, and organizational measures designed to protect information, including encryption in transit and access restrictions. No method of transmission or storage is completely secure; please use a strong password and keep your device updated.',
      '## 10. International Transfers',
      'Your information may be processed in countries other than where you live. Where required, we use appropriate safeguards (such as standard contractual clauses or equivalent mechanisms) for cross-border transfers.',
      '## 11. Children',
      'The Service is not directed to children under 13 (or the minimum age in your country). We do not knowingly collect personal information from children without appropriate parental consent. Contact us if you believe a child has provided data without consent.',
      '## 12. Third-Party Services',
      'The Service may link to or integrate with third-party websites, app stores, sign-in providers, or professional services. Their privacy practices are governed by their own policies. We encourage you to review those policies before sharing information with them.',
      '## 13. Cookies and Similar Technologies',
      'If you use our website or web-based features, we may use cookies or similar technologies for authentication, preferences, and analytics. You can manage browser cookie settings where applicable.',
      '## 14. Changes to This Policy',
      'We may update this Privacy Policy from time to time. We will post the updated version in the app and revise the "Last updated" date. Material changes may be communicated via in-app notice or email where appropriate. Continued use after the effective date means you acknowledge the updated policy, unless your local law requires additional consent.',
      '## 15. Contact Us',
      'For privacy questions, requests, or complaints, email support@nouracare.app. You may also have the right to contact your local data protection authority.',
    ].join('\n'),
  },
  zh: {
    effectiveDate: '最后更新：2026年6月1日',
    body: [
      '本隐私政策说明 NouraCare（「我们」）在您使用 NouraCare 移动应用、网站及相关服务（「服务」）时如何收集、使用、存储和共享信息。使用服务即表示您同意本政策所述做法；如不同意，请勿使用服务。',
      '## 1. 我们是谁',
      'NouraCare 提供月经周期、生育力、怀孕及相关健康追踪的数字工具。隐私相关问题或请求请联系 support@nouracare.app。',
      '## 2. 我们收集的信息',
      '我们收集以下类别的信息：（a）账户信息——姓名、电子邮件、电话号码（如提供）、头像及登录提供方的身份标识；（b）您输入的健康数据——包括周期日期、症状、情绪、笔记、怀孕信息、生育记录及提醒；（c）设备与应用数据——设备类型、操作系统、应用版本、语言及一般诊断日志；（d）使用数据——使用的功能、交互事件及崩溃报告；（e）通信内容——您提交的支持消息、反馈及社区帖子；（f）可选分析——若在设置中启用匿名数据共享，我们可能收集汇总或去标识化的使用统计以改进服务。',
      '## 3. 我们如何使用信息',
      '我们使用信息以：提供并个性化服务（含预测与提醒）；在您登录时在设备间同步数据；运营社区、咨询及教育功能；发送您请求的通知；维护安全并防止滥用；分析性能并修复错误；履行法律义务；以及在法律要求时经您同意通过可选分析改进服务。',
      '## 4. 处理的法律依据',
      '根据您所在地区，我们基于以下依据处理个人数据：履行与您的合同（提供服务）；您的同意（例如可选分析或特定通知）；在安全、产品改进与支持方面与您的权利平衡后的合法利益；以及遵守法律义务。',
      '## 5. 我们如何共享信息',
      '我们不出售您的个人健康信息。我们可能在以下情况共享信息：（a）与在保密义务下协助我们托管、存储、分析、发送邮件或支持服务的提供商；（b）与您通过可选咨询功能选择连接的医疗专业人员或平台；（c）法律、法规、法律程序要求，或为保护权利、安全；（d）与合并、收购或资产出售相关，并继续受保护；（e）经您明确指示或同意。无法合理识别您的汇总或去标识化数据可用于分析与报告。',
      '## 6. 敏感健康数据',
      '您在 NouraCare 中记录的健康信息被视为敏感信息。我们采用访问控制、传输加密等额外保障。您控制输入内容，可使用隐私设置（包括在锁屏隐藏敏感通知内容）减少在设备上的暴露。',
      '## 7. 您的选择与权利',
      '根据适用法律，您可能有权访问、更正、导出、限制或删除个人数据；在基于同意的处理中撤回同意；以及对某些处理提出异议。您可在设置中导出数据或请求删除账户，并可关闭可选匿名数据共享。行使权利请联系 support@nouracare.app，我们可能需要验证身份。',
      '## 8. 数据保留',
      '我们在账户活跃期间或提供服务所需期间保留信息，亦用于解决争议、执行协议及遵守法律。删除账户后，我们将在合理期限内删除或匿名化个人数据，法律、安全或备份要求的保留除外。',
      '## 9. 安全',
      '我们采用管理、技术及组织措施保护信息，包括传输加密与访问限制。任何传输或存储方式都无法完全安全；请使用强密码并保持设备更新。',
      '## 10. 跨境传输',
      '您的信息可能在您居住国以外的国家处理。在需要时，我们采用适当保障措施（如标准合同条款或同等机制）进行跨境传输。',
      '## 11. 儿童',
      '服务不面向 13 岁以下儿童（或您所在国家/地区的最低年龄）。未经适当父母同意，我们不会故意收集儿童个人信息。如认为儿童在未获同意情况下提供了数据，请联系我们。',
      '## 12. 第三方服务',
      '服务可能链接或集成第三方网站、应用商店、登录提供方或专业服务。其隐私做法受其自身政策约束。建议在向其共享信息前查阅相关政策。',
      '## 13. Cookie 及类似技术',
      '若您使用我们的网站或 Web 功能，我们可能使用 Cookie 或类似技术进行身份验证、偏好设置及分析。可在适用情况下管理浏览器 Cookie 设置。',
      '## 14. 政策变更',
      '我们可能不时更新本隐私政策，并在应用中发布更新版本及修订「最后更新」日期。重大变更可能通过应用内通知或电子邮件告知。在法律未要求额外同意的情况下，生效日后继续使用即表示您知悉更新后的政策。',
      '## 15. 联系我们',
      '隐私问题、请求或投诉请发送邮件至 support@nouracare.app。您也可能有权联系当地数据保护机构。',
    ].join('\n'),
  },
  ms: {
    effectiveDate: 'Kemas kini terakhir: 1 Jun 2026',
    body: [
      'Dasar Privasi ini menerangkan cara NouraCare ("kami") mengumpul, menggunakan, menyimpan, dan berkongsi maklumat apabila anda menggunakan aplikasi mudah alih, laman web, dan perkhidmatan berkaitan NouraCare ("Perkhidmatan"). Dengan menggunakan Perkhidmatan, anda bersetuju dengan amalan yang diterangkan di sini.',
      '## 1. Siapa Kami',
      'NouraCare menyediakan alat digital untuk menjejak kitaran haid, kesuburan, kehamilan, dan kesejahteraan berkaitan. Untuk soalan atau permintaan privasi, hubungi support@nouracare.app.',
      '## 2. Maklumat Yang Kami Kumpul',
      'Kami mengumpul: (a) maklumat akaun — nama, e-mel, telefon (jika diberikan), foto profil, dan pengenalan log masuk; (b) data kesihatan yang anda masukkan — tarikh kitaran, simptom, mood, nota, maklumat kehamilan, log kesuburan, dan peringatan; (c) data peranti dan aplikasi; (d) data penggunaan — ciri yang digunakan, acara interaksi, laporan ranap; (e) komunikasi — mesej sokongan, maklum balas, dan siaran komuniti; (f) analitik pilihan — jika anda mendayakan perkongsian data tanpa nama dalam Tetapan.',
      '## 3. Cara Kami Menggunakan Maklumat',
      'Kami menggunakan maklumat untuk menyediakan dan memperibadikan Perkhidmatan, menyegerakkan data merentas peranti, mengendalikan ciri komuniti dan pendidikan, menghantar notifikasi, mengekalkan keselamatan, menganalisis prestasi, mematuhi undang-undang, dan — dengan persetujuan anda jika diperlukan — menambah baik Perkhidmatan melalui analitik pilihan.',
      '## 4. Asas Undang-undang Pemprosesan',
      'Bergantung pada lokasi anda, kami memproses data peribadi berdasarkan pelaksanaan kontrak dengan anda, persetujuan anda, kepentingan sah kami (keselamatan dan penambahbaikan produk) yang diimbangi dengan hak anda, dan pematuhan kewajipan undang-undang.',
      '## 5. Cara Kami Berkongsi Maklumat',
      'Kami tidak menjual maklumat kesihatan peribadi anda. Kami boleh berkongsi maklumat dengan penyedia perkhidmatan di bawah kewajipan kerahsiaan, profesional kesihatan atau platform yang anda pilih untuk disambungkan, apabila dikehendaki oleh undang-undang, berkaitan penggabungan atau pemerolehan, atau dengan arahan atau persetujuan anda yang jelas.',
      '## 6. Data Kesihatan Sensitif',
      'Maklumat kesihatan yang anda log direkodkan sebagai sensitif. Kami menggunakan langkah perlindungan tambahan termasuk kawalan akses dan penyulitan semasa penghantaran. Anda mengawal apa yang dimasukkan dan boleh menggunakan tetapan privasi (termasuk menyembunyikan kandungan notifikasi sensitif pada skrin kunci).',
      '## 7. Pilihan dan Hak Anda',
      'Anda mungkin berhak mengakses, membetulkan, mengeksport, mengehadkan, atau memadam data peribadi; menarik balik persetujuan; dan membantah pemprosesan tertentu. Eksport atau pemadaman akaun tersedia dalam Tetapan. Hubungi support@nouracare.app untuk melaksanakan hak anda.',
      '## 8. Pengekalan Data',
      'Kami mengekalkan maklumat selagi akaun anda aktif atau diperlukan untuk menyediakan Perkhidmatan dan mematuhi undang-undang. Apabila anda memadam akaun, kami memadam atau tanpa nama data peribadi dalam tempoh munasabah, kecuali pengekalan diperlukan untuk undang-undang, keselamatan, atau sandaran.',
      '## 9. Keselamatan',
      'Kami menggunakan langkah pentadbiran, teknikal, dan organisasi termasuk penyulitan semasa penghantaran. Tiada kaedah penghantaran atau storan yang sepenuhnya selamat; gunakan kata laluan yang kuat dan pastikan peranti dikemas kini.',
      '## 10. Pemindahan Antarabangsa',
      'Maklumat anda mungkin diproses di negara selain tempat tinggal anda. Di mana diperlukan, kami menggunakan perlindungan yang sesuai untuk pemindahan rentas sempadan.',
      '## 11. Kanak-kanak',
      'Perkhidmatan tidak ditujukan kepada kanak-kanak di bawah 13 tahun (atau umur minimum di negara anda). Kami tidak sengaja mengumpul maklumat peribadi kanak-kanak tanpa persetujuan ibu bapa yang sesuai.',
      '## 12. Perkhidmatan Pihak Ketiga',
      'Perkhidmatan mungkin dipautkan atau disepadukan dengan laman web, gedung aplikasi, penyedia log masuk, atau perkhidmatan profesional pihak ketiga. Amalan privasi mereka dikawal oleh dasar mereka sendiri.',
      '## 13. Kuki dan Teknologi Serupa',
      'Jika anda menggunakan laman web kami, kami mungkin menggunakan kuki untuk pengesahan, keutamaan, dan analitik. Anda boleh mengurus tetapan kuki pelayar jika berkenaan.',
      '## 14. Perubahan kepada Dasar Ini',
      'Kami boleh mengemas kini Dasar Privasi ini dan memaparkan versi terkini dalam aplikasi. Perubahan material boleh dimaklumkan melalui notis dalam aplikasi atau e-mel.',
      '## 15. Hubungi Kami',
      'Untuk soalan, permintaan, atau aduan privasi, e-mel support@nouracare.app. Anda juga mungkin berhak menghubungi pihak berkuasa perlindungan data tempatan anda.',
    ].join('\n'),
  },
  fa: {
    effectiveDate: 'آخرین به‌روزرسانی: ۱ ژوئن ۲۰۲۶',
    body: [
      'این سیاست حریم خصوصی توضیح می‌دهد NouraCare («ما») هنگام استفاده از اپلیکیشن، وب‌سایت و خدمات مرتبط («خدمات») چگونه اطلاعات را جمع‌آوری، استفاده، نگهداری و به اشتراک می‌گذارد. با استفاده از خدمات، این شیوه‌ها را می‌پذیرید.',
      '## ۱. ما کیستیم',
      'NouraCare ابزارهای دیجیتال برای ثبت چرخه قاعدگی، باروری، بارداری و سلامت مرتبط ارائه می‌دهد. برای پرسش یا درخواست حریم خصوصی: support@nouracare.app',
      '## ۲. اطلاعاتی که جمع‌آوری می‌کنیم',
      'دسته‌های زیر: (الف) اطلاعات حساب — نام، ایمیل، تلفن (در صورت ارائه)، عکس پروفایل و شناسه‌های ورود؛ (ب) داده‌های سلامت که وارد می‌کنید — تاریخ پریود، علائم، خلق، یادداشت، بارداری، باروری و یادآورها؛ (ج) دادهٔ دستگاه و برنامه؛ (د) دادهٔ استفاده — امکانات استفاده‌شده، رویدادها و گزارش خرابی؛ (ه) ارتباطات — پیام پشتیبانی، بازخورد و پست‌های انجمن؛ (و) تحلیل اختیاری — در صورت فعال‌سازی اشتراک داده ناشناس در تنظیمات.',
      '## ۳. نحوهٔ استفاده از اطلاعات',
      'برای ارائه و شخصی‌سازی خدمات (از جمله پیش‌بینی و یادآور)، همگام‌سازی بین دستگاه‌ها، امکانات اجتماعی و آموزشی، ارسال اعلان‌های درخواستی، امنیت، رفع اشکال، رعایت قانون و — با رضایت در صورت نیاز — بهبود خدمات از طریق تحلیل اختیاری استفاده می‌کنیم.',
      '## ۴. مبانی قانونی پردازش',
      'بسته به محل اقامت شما، پردازش بر اساس اجرای قرارداد، رضایت شما، منافع مشروع ما (امنیت و بهبود محصول) متناسب با حقوق شما، و الزامات قانونی انجام می‌شود.',
      '## ۵. نحوهٔ اشتراک‌گذاری',
      'اطلاعات سلامت شخصی شما فروخته نمی‌شود. ممکن است با ارائه‌دهندگان خدمات تحت تعهد محرمانگی، متخصصانی که خودتان انتخاب می‌کنید، در صورت الزام قانونی، در ادغام یا فروش دارایی، یا با رضایت صریح شما به اشتراک گذاشته شود. دادهٔ تجمیع‌شده یا ناشناس برای گزارش استفاده می‌شود.',
      '## ۶. دادهٔ حساس سلامت',
      'اطلاعات سلامتی که ثبت می‌کنید حساس تلقی می‌شود. از کنترل دسترسی و رمزنگاری در انتقال استفاده می‌کنیم. شما کنترل ورودی دارید و می‌توانید از تنظیمات حریم خصوصی (از جمله پنهان کردن اعلان‌های حساس در صفحه قفل) استفاده کنید.',
      '## ۷. انتخاب‌ها و حقوق شما',
      'ممکن است حق دسترسی، اصلاح، خروجی گرفتن، محدود یا حذف داده، پس گرفتن رضایت و اعتراض داشته باشید. از تنظیمات می‌توانید داده را خروجی بگیرید یا حساب را حذف کنید و اشتراک ناشناس را خاموش کنید. برای اجرای حقوق: support@nouracare.app',
      '## ۸. نگهداری داده',
      'تا زمانی که حساب فعال است یا برای ارائه خدمات لازم است نگه می‌داریم. پس از حذف حساب، در مدت معقول داده را حذف یا ناشناس می‌کنیم، مگر نگهداری قانونی، امنیتی یا پشتیبان لازم باشد.',
      '## ۹. امنیت',
      'از اقدامات مدیریتی، فنی و سازمانی از جمله رمزنگاری در انتقال استفاده می‌کنیم. هیچ روشی کاملاً امن نیست؛ رمز قوی و به‌روز بودن دستگاه را رعایت کنید.',
      '## ۱۰. انتقال بین‌المللی',
      'اطلاعات ممکن است خارج از کشور محل اقامت شما پردازش شود. در صورت نیاز از تضمین‌های مناسب برای انتقال مرزی استفاده می‌کنیم.',
      '## ۱۱. کودکان',
      'خدمات برای زیر ۱۳ سال (یا حداقل سن کشور شما) طراحی نشده است. آگاهانه بدون رضایت والدین دادهٔ کودک جمع نمی‌کنیم.',
      '## ۱۲. خدمات شخص ثالث',
      'ممکن است به وب‌سایت‌ها، فروشگاه برنامه، ارائه‌دهندگان ورود یا خدمات حرفه‌ای شخص ثالث متصل شوید. سیاست حریم خصوصی آن‌ها مستقل است.',
      '## ۱۳. کوکی و فناوری مشابه',
      'در وب‌سایت یا امکانات وب ممکن است از کوکی برای احراز هویت، ترجیحات و تحلیل استفاده شود.',
      '## ۱۴. تغییر این سیاست',
      'ممکن است این سیاست را به‌روز کنیم و نسخهٔ جدید را در برنامه با تاریخ «آخرین به‌روزرسانی» منتشر کنیم. تغییرات مهم ممکن است از طریق اعلان درون‌برنامه یا ایمیل اطلاع داده شود.',
      '## ۱۵. تماس با ما',
      'برای پرسش، درخواست یا شکایت حریم خصوصی: support@nouracare.app. ممکن است حق تماس با مرجع حفاظت داده در کشور خود را داشته باشید.',
    ].join('\n'),
  },
} as const;
