/** Auto-generated school week strings (MS). */
export const SCHOOL_WEEK_MS: Record<string, string> = {
  "school.dev.default": "Bayi anda sedang membesar dan berkembang dengan sihat! Setiap minggu membawa pencapaian baharu dan perubahan yang menakjubkan.",
  "school.fun.default": "Bayi anda sedang membesar dan berkembang dengan sihat! Setiap minggu membawa pencapaian baharu dan perubahan yang menakjubkan.",
  "school.length.default": "Sedang membesar...",
  "school.dev.w4": "Bayi anda masih hanya sekelompok sel kecil yang dipanggil blastosista, tetapi asas untuk segalanya sedang dibina!",
  "school.fun.w4": "Pada peringkat ini, bayi anda lebih kecil daripada sebutir beras!",
  "school.length.w4": "0.04 inci",
  "school.dev.w5": "Jantung mula terbentuk dan akan mula berdegup tidak lama lagi. Tiub neural (yang menjadi otak dan sumsum tulang belakang) sedang berkembang.",
  "school.fun.w5": "Jantung bayi anda akan berdegup kira-kira 100,000 kali sehari!",
  "school.length.w5": "0.13 inci",
  "school.dev.w6": "Jantung bayi anda kini berdegup! Mata, telinga, dan mulut mula terbentuk. Bayi kira-kira saiz sekeping kacang dal.",
  "school.fun.w6": "Jantung bayi anda berdegup dua kali lebih laju daripada anda!",
  "school.length.w6": "0.25 inci",
  "school.dev.w7": "Lengan dan kaki bayi mula terbentuk sebagai tunas kecil. Otak berkembang pesat dengan 100 sel otak baharu setiap minit!",
  "school.fun.w7": "Bayi anda berkembang dengan kadar yang luar biasa — kira-kira 1 juta sel baharu setiap minit!",
  "school.length.w7": "0.5 inci",
  "school.dev.w8": "Jari tangan dan kaki mula terbentuk! Ciri-ciri muka bayi semakin jelas. Ekor sedang hilang.",
  "school.fun.w8": "Cap jari bayi anda sudah mula terbentuk dan akan menjadi unik!",
  "school.length.w8": "0.63 inci",
  "school.dev.w9": "Semua organ utama sudah ada dan mula berfungsi. Bayi kini boleh bergerak, walaupun anda belum merasainya.",
  "school.fun.w9": "Bayi anda kini boleh membuat gerakan kecil, walaupun anda belum merasainya!",
  "school.length.w9": "0.9 inci",
  "school.dev.w10": "Tulang bayi mula mengeras. Bayi kini boleh menggenggam dan mempunyai jari tangan serta kaki yang berasingan.",
  "school.fun.w10": "Otak bayi anda membesar dengan kadar yang menakjubkan — kira-kira 250,000 neuron baharu setiap minit!",
  "school.length.w10": "1.22 inci",
  "school.dev.w11": "Bayi mula kelihatan lebih seperti manusia! Kepala kira-kira separuh saiz badan. Bayi kini boleh menelan dan membuat gerakan pernafasan.",
  "school.fun.w11": "Bayi anda kini boleh menelan dan mungkin menghisap ibu jari!",
  "school.length.w11": "1.61 inci",
  "school.dev.w12": "Refleks bayi sedang berkembang. Bayi kini boleh membuat ekspresi muka dan mungkin menghisap ibu jari!",
  "school.fun.w12": "Refleks bayi anda sedang berkembang — mereka kini boleh menggenggam!",
  "school.length.w12": "2.13 inci",
  "school.dev.w13": "Pita suara bayi sedang berkembang. Bayi kini boleh mendengar bunyi dari luar rahim.",
  "school.fun.w13": "Bayi anda kini boleh mendengar bunyi dari luar rahim!",
  "school.length.w13": "2.91 inci",
  "school.dev.w14": "Cap jari bayi sedang terbentuk! Bayi kini boleh membuat ekspresi muka dan mungkin tersenyum.",
  "school.fun.w14": "Cap jari bayi anda sudah terbentuk sepenuhnya dan unik!",
  "school.length.w14": "3.42 inci",
  "school.dev.w15": "Tulang bayi semakin kuat. Bayi kini boleh membuat gerakan terkoordinasi dan mungkin menendang!",
  "school.fun.w15": "Bayi anda kini boleh membuat ekspresi muka dan mungkin tersenyum!",
  "school.length.w15": "3.98 inci",
  "school.dev.w16": "Mata bayi kini boleh bergerak dan mengesan cahaya. Deria rasa bayi sedang berkembang.",
  "school.fun.w16": "Deria rasa bayi anda sedang berkembang dan boleh merasai cecair amnion!",
  "school.length.w16": "4.57 inci",
  "school.dev.w17": "Pendengaran bayi semakin baik. Bayi kini boleh mendengar degupan jantung dan suara anda!",
  "school.fun.w17": "Bayi anda kini boleh mendengar degupan jantung dan suara anda!",
  "school.length.w17": "5.12 inci",
  "school.dev.w18": "Gerakan bayi semakin terkoordinasi. Bayi kini boleh menguap dan ceguk.",
  "school.fun.w18": "Bayi anda kini boleh menguap dan ceguk!",
  "school.length.w18": "5.59 inci",
  "school.dev.w19": "Otak bayi berkembang pesat. Bayi kini boleh bertindak balas terhadap sentuhan dan mungkin memegang tali pusat.",
  "school.fun.w19": "Bayi anda kini boleh bertindak balas terhadap sentuhan dan mungkin memegang tali pusat!",
  "school.length.w19": "6.02 inci",
  "school.dev.w20": "Bayi sudah separuh jalan kehamilan! Bayi kini boleh mendengar dan bertindak balas terhadap bunyi dari luar rahim.",
  "school.fun.w20": "Bayi anda sudah separuh jalan kehamilan dan kini boleh mendengar serta bertindak balas terhadap bunyi!",
  "school.length.w20": "6.46 inci",
  "school.dev.w21": "Sistem pencernaan bayi sedang berkembang. Bayi kini boleh merasai cecair amnion.",
  "school.fun.w21": "Bayi anda kini boleh merasai cecair amnion dan mungkin mempunyai pilihan makanan!",
  "school.length.w21": "10.51 inci",
  "school.dev.w22": "Deria sentuhan bayi sedang berkembang. Bayi kini boleh merasa apabila anda menyentuh perut.",
  "school.fun.w22": "Bayi anda kini boleh merasa apabila anda menyentuh perut!",
  "school.length.w22": "10.94 inci",
  "school.dev.w23": "Paru-paru bayi berkembang pesat. Bayi kini boleh membuat gerakan pernafasan.",
  "school.fun.w23": "Bayi anda kini boleh membuat gerakan pernafasan!",
  "school.length.w23": "11.38 inci",
  "school.dev.w24": "Mata bayi sudah terbentuk sepenuhnya dan kini boleh membuka dan menutup. Bayi boleh melihat cahaya yang menembusi rahim.",
  "school.fun.w24": "Mata bayi anda kini boleh membuka dan menutup serta melihat cahaya!",
  "school.length.w24": "11.81 inci",
  "school.dev.w25": "Otak bayi berkembang pesat. Bayi kini boleh bermimpi dan mempunyai kitaran tidur.",
  "school.fun.w25": "Bayi anda kini boleh bermimpi dan mempunyai kitaran tidur!",
  "school.length.w25": "13.62 inci",
  "school.dev.w26": "Paru-paru bayi menghasilkan surfaktan, yang membantu bernafas selepas lahir.",
  "school.fun.w26": "Bayi anda kini boleh bertindak balas terhadap suara anda dan mungkin mengenalinya!",
  "school.length.w26": "14.02 inci",
  "school.dev.w27": "Sistem imun bayi sedang berkembang. Bayi kini boleh bertindak balas terhadap suara anda dan mungkin mengenalinya.",
  "school.fun.w27": "Bayi anda kini boleh membezakan bunyi yang berbeza!",
  "school.length.w27": "14.41 inci",
  "school.dev.w28": "Mata bayi kini boleh fokus dan menjejaki cahaya. Bayi kini boleh membezakan bunyi yang berbeza.",
  "school.fun.w28": "Bayi anda kini boleh fokus dan menjejaki cahaya!",
  "school.length.w28": "14.80 inci",
  "school.dev.w29": "Tulang bayi sudah terbentuk sepenuhnya tetapi masih lembut. Bayi kini boleh membuat gerakan terkoordinasi.",
  "school.fun.w29": "Bayi anda kini boleh membuat gerakan terkoordinasi!",
  "school.length.w29": "15.2 inci",
  "school.dev.w30": "Otak bayi berkembang pesat. Bayi kini boleh belajar dan mengingati bunyi dari luar rahim.",
  "school.fun.w30": "Bayi anda kini boleh belajar dan mengingati bunyi dari luar rahim!",
  "school.length.w30": "15.71 inci",
  "school.dev.w31": "Paru-paru bayi hampir sepenuhnya berkembang. Bayi kini boleh berlatih gerakan pernafasan.",
  "school.fun.w31": "Bayi anda kini boleh berlatih gerakan pernafasan!",
  "school.length.w31": "16.18 inci",
  "school.dev.w32": "Kulit bayi semakin kurang lut sinar. Bayi kini boleh membuat ekspresi muka.",
  "school.fun.w32": "Bayi anda kini boleh membuat ekspresi muka!",
  "school.length.w32": "16.69 inci",
  "school.dev.w33": "Sistem imun bayi semakin kuat. Bayi kini boleh bertindak balas terhadap sentuhan anda.",
  "school.fun.w33": "Bayi anda kini boleh bertindak balas terhadap sentuhan anda!",
  "school.length.w33": "17.20 inci",
  "school.dev.w34": "Paru-paru bayi sudah sepenuhnya berkembang. Bayi kini boleh bernafas sendiri jika dilahirkan pramatang.",
  "school.fun.w34": "Bayi anda kini boleh bernafas sendiri jika dilahirkan pramatang!",
  "school.length.w34": "17.72 inci",
  "school.dev.w35": "Otak bayi berkembang pesat. Bayi kini boleh belajar dan mengingati corak.",
  "school.fun.w35": "Bayi anda kini boleh belajar dan mengingati corak!",
  "school.length.w35": "18.19 inci",
  "school.dev.w36": "Kepala bayi kini dalam kedudukan untuk kelahiran. Bayi kini boleh membuat gerakan terkoordinasi.",
  "school.fun.w36": "Bayi anda kini boleh membuat gerakan terkoordinasi!",
  "school.length.w36": "18.66 inci",
  "school.dev.w37": "Bayi dianggap cukup bulan! Bayi kini boleh hidup di luar rahim dengan sokongan minimum.",
  "school.fun.w37": "Bayi anda dianggap cukup bulan dan boleh hidup di luar rahim!",
  "school.length.w37": "19.13 inci",
  "school.dev.w38": "Otak bayi berkembang pesat. Bayi kini boleh belajar dan mengingati bunyi.",
  "school.fun.w38": "Bayi anda kini boleh belajar dan mengingati bunyi!",
  "school.length.w38": "19.61 inci",
  "school.dev.w39": "Paru-paru bayi sudah sepenuhnya berkembang. Bayi kini boleh bernafas sendiri.",
  "school.fun.w39": "Bayi anda kini boleh bernafas sendiri!",
  "school.length.w39": "19.96 inci",
  "school.dev.w40": "Bayi sedia dilahirkan! Bayi kini boleh hidup di luar rahim dengan sokongan penuh.",
  "school.fun.w40": "Bayi anda sedia dilahirkan dan boleh hidup di luar rahim!",
  "school.length.w40": "20.16 inci",
  "school.size.w4": "Biji Bunga Poppy 🌱",
  "school.sizeDesc.w4": "Kecil seperti biji poppy",
  "school.size.w5": "Biji Bijan 🌱",
  "school.sizeDesc.w5": "Kecil seperti biji bijan",
  "school.size.w6": "Kacang Dal 🌱",
  "school.sizeDesc.w6": "Saiz sekeping kacang dal",
  "school.size.w7": "Blueberi 🫐",
  "school.sizeDesc.w7": "Manis seperti blueberi",
  "school.size.w8": "Kacang Rajah 🫘",
  "school.sizeDesc.w8": "Bentuk seperti kacang rajah",
  "school.size.w9": "Anggur 🍇",
  "school.sizeDesc.w9": "Montok seperti anggur",
  "school.size.w10": "Kumquat 🍊",
  "school.sizeDesc.w10": "Saiz kumquat",
  "school.size.w11": "Ara 🫒",
  "school.sizeDesc.w11": "Saiz buah ara",
  "school.size.w12": "Lime 🍋",
  "school.sizeDesc.w12": "Saiz lime",
  "school.size.w13": "Pic 🍑",
  "school.sizeDesc.w13": "Saiz pic",
  "school.size.w14": "Lemon 🍋",
  "school.sizeDesc.w14": "Saiz lemon",
  "school.size.w15": "Epal 🍎",
  "school.sizeDesc.w15": "Saiz epal",
  "school.size.w16": "Avokado 🥑",
  "school.sizeDesc.w16": "Saiz avokado",
  "school.size.w17": "Pir 🍐",
  "school.sizeDesc.w17": "Saiz pir",
  "school.size.w18": "Lada Berek 🫑",
  "school.sizeDesc.w18": "Saiz lada berek",
  "school.size.w19": "Mangga 🥭",
  "school.sizeDesc.w19": "Saiz mangga",
  "school.size.w20": "Pisang 🍌",
  "school.sizeDesc.w20": "Panjang pisang",
  "school.size.w21": "Lobak Merah 🥕",
  "school.sizeDesc.w21": "Panjang lobak merah",
  "school.size.w22": "Kelapa 🥥",
  "school.sizeDesc.w22": "Saiz kelapa",
  "school.size.w23": "Grapefruit 🍊",
  "school.sizeDesc.w23": "Saiz grapefruit",
  "school.size.w24": "Jagung 🌽",
  "school.sizeDesc.w24": "Panjang tongkol jagung",
  "school.size.w25": "Kembang Kol 🥦",
  "school.sizeDesc.w25": "Saiz kembang kol",
  "school.size.w26": "Salad 🥬",
  "school.sizeDesc.w26": "Saiz kepala salad",
  "school.size.w27": "Brokoli 🥦",
  "school.sizeDesc.w27": "Saiz brokoli",
  "school.size.w28": "Terung 🍆",
  "school.sizeDesc.w28": "Saiz terung",
  "school.size.w29": "Labu Butternut 🎃",
  "school.sizeDesc.w29": "Saiz labu",
  "school.size.w30": "Kubis 🥬",
  "school.sizeDesc.w30": "Saiz kubis",
  "school.size.w31": "Nanas 🍍",
  "school.sizeDesc.w31": "Saiz nanas",
  "school.size.w32": "Labu 🎃",
  "school.sizeDesc.w32": "Labu besar",
  "school.size.w33": "Tembikai Susu 🍈",
  "school.sizeDesc.w33": "Saiz tembikai",
  "school.size.w34": "Tembaikai 🍈",
  "school.sizeDesc.w34": "Saiz tembikai",
  "school.size.w35": "Tembaikai Susu 🍈",
  "school.sizeDesc.w35": "Tembaikai susu",
  "school.size.w36": "Salad Romaine 🥬",
  "school.sizeDesc.w36": "Saiz salad romaine",
  "school.size.w37": "Swiss Chard 🥬",
  "school.sizeDesc.w37": "Saiz swiss chard",
  "school.size.w38": "Daun Bawang Perai 🧅",
  "school.sizeDesc.w38": "Panjang daun bawang perai",
  "school.size.w39": "Tembikai Mini 🍉",
  "school.sizeDesc.w39": "Tembikai mini",
  "school.size.w40": "Tembikai 🍉",
  "school.sizeDesc.w40": "Saiz tembikai penuh"
};
