/** Auto-generated school week strings (ZH). */
export const SCHOOL_WEEK_ZH: Record<string, string> = {
  "school.dev.default": "宝宝正在健康地成长发育！每一周都会带来新的里程碑和惊人的变化。",
  "school.fun.default": "宝宝正在健康地成长发育！每一周都会带来新的里程碑和惊人的变化。",
  "school.length.default": "成长中...",
  "school.dev.w4": "宝宝还只是一个称为囊胚的微小细胞球，但一切的基础正在奠定！",
  "school.fun.w4": "在这个阶段，宝宝比一粒米还小！",
  "school.length.w4": "0.04 英寸",
  "school.dev.w5": "心脏开始形成，很快就要开始跳动。神经管（将发育成大脑和脊髓）正在发育。",
  "school.fun.w5": "宝宝的心脏每天大约跳动 10 万次！",
  "school.length.w5": "0.13 英寸",
  "school.dev.w6": "宝宝的心脏现在开始跳动了！眼睛、耳朵和嘴巴开始形成。宝宝大约有一颗扁豆那么大。",
  "school.fun.w6": "宝宝的心跳速度是您的两倍！",
  "school.length.w6": "0.25 英寸",
  "school.dev.w7": "宝宝的手臂和腿开始以小小的芽状突起形成。大脑正在快速发育，每分钟产生 10 万个新脑细胞！",
  "school.fun.w7": "宝宝正以惊人的速度发育——每分钟约 100 万个新细胞！",
  "school.length.w7": "0.5 英寸",
  "school.dev.w8": "手指和脚趾开始形成！宝宝的面部特征更加清晰。尾巴正在消失。",
  "school.fun.w8": "宝宝的指纹已经在形成，而且将是独一无二的！",
  "school.length.w8": "0.63 英寸",
  "school.dev.w9": "所有主要器官都已就位并开始运作。宝宝现在可以活动了，但您还感觉不到。",
  "school.fun.w9": "宝宝现在可以做出微小的动作，但您还感觉不到！",
  "school.length.w9": "0.9 英寸",
  "school.dev.w10": "宝宝的骨骼开始变硬。宝宝现在可以握拳，手指和脚趾已经分开。",
  "school.fun.w10": "宝宝的大脑正以惊人的速度生长——每分钟约 25 万个新神经元！",
  "school.length.w10": "1.22 英寸",
  "school.dev.w11": "宝宝开始看起来更像人了！头部约占身体的一半。宝宝现在可以吞咽并做出呼吸动作。",
  "school.fun.w11": "宝宝现在可以吞咽，甚至可能吮吸拇指！",
  "school.length.w11": "1.61 英寸",
  "school.dev.w12": "宝宝的反射正在发育。宝宝现在可以做出面部表情，甚至可能吮吸拇指！",
  "school.fun.w12": "宝宝的反射正在发育——现在可以握拳了！",
  "school.length.w12": "2.13 英寸",
  "school.dev.w13": "宝宝的声带正在发育。宝宝现在可以听到子宫外的声音。",
  "school.fun.w13": "宝宝现在可以听到子宫外的声音了！",
  "school.length.w13": "2.91 英寸",
  "school.dev.w14": "宝宝的指纹正在形成！宝宝现在可以做出面部表情，甚至可能微笑。",
  "school.fun.w14": "宝宝的指纹已完全形成，而且独一无二！",
  "school.length.w14": "3.42 英寸",
  "school.dev.w15": "宝宝的骨骼正在变强。宝宝现在可以做出协调的动作，甚至可能踢腿！",
  "school.fun.w15": "宝宝现在可以做出面部表情，甚至可能微笑！",
  "school.length.w15": "3.98 英寸",
  "school.dev.w16": "宝宝的眼睛现在可以移动并感知光线。宝宝的味蕾正在发育。",
  "school.fun.w16": "宝宝的味蕾正在发育，可以品尝羊水了！",
  "school.length.w16": "4.57 英寸",
  "school.dev.w17": "宝宝的听力正在改善。宝宝现在可以听到您的心跳和声音！",
  "school.fun.w17": "宝宝现在可以听到您的心跳和声音了！",
  "school.length.w17": "5.12 英寸",
  "school.dev.w18": "宝宝的动作越来越协调。宝宝现在可以打哈欠和打嗝了。",
  "school.fun.w18": "宝宝现在可以打哈欠和打嗝了！",
  "school.length.w18": "5.59 英寸",
  "school.dev.w19": "宝宝的大脑正在快速发育。宝宝现在可以对触摸做出反应，甚至可能抓住脐带。",
  "school.fun.w19": "宝宝现在可以对触摸做出反应，甚至可能抓住脐带！",
  "school.length.w19": "6.02 英寸",
  "school.dev.w20": "孕期已过半！宝宝现在可以听到并回应子宫外的声音。",
  "school.fun.w20": "孕期已过半，宝宝现在可以听到并回应声音了！",
  "school.length.w20": "6.46 英寸",
  "school.dev.w21": "宝宝的消化系统正在发育。宝宝现在可以品尝羊水了。",
  "school.fun.w21": "宝宝现在可以品尝羊水，甚至可能对食物有偏好！",
  "school.length.w21": "10.51 英寸",
  "school.dev.w22": "宝宝的触觉正在发育。宝宝现在可以感受到您抚摸腹部。",
  "school.fun.w22": "宝宝现在可以感受到您抚摸腹部了！",
  "school.length.w22": "10.94 英寸",
  "school.dev.w23": "宝宝的肺部正在快速发育。宝宝现在可以做出呼吸动作。",
  "school.fun.w23": "宝宝现在可以做出呼吸动作了！",
  "school.length.w23": "11.38 英寸",
  "school.dev.w24": "宝宝的眼睛已完全形成，现在可以睁开和闭合。宝宝可以看到透过子宫的光线。",
  "school.fun.w24": "宝宝的眼睛现在可以睁开和闭合，并能感知光线了！",
  "school.length.w24": "11.81 英寸",
  "school.dev.w25": "宝宝的大脑正在快速发育。宝宝现在可以做梦并有睡眠周期。",
  "school.fun.w25": "宝宝现在可以做梦并有睡眠周期了！",
  "school.length.w25": "13.62 英寸",
  "school.dev.w26": "宝宝的肺部正在产生表面活性剂，这有助于出生后呼吸。",
  "school.fun.w26": "宝宝现在可以对您的声音做出反应，甚至可能认出来了！",
  "school.length.w26": "14.02 英寸",
  "school.dev.w27": "宝宝的免疫系统正在发育。宝宝现在可以对您的声音做出反应，甚至可能认出来了。",
  "school.fun.w27": "宝宝现在可以区分不同的声音了！",
  "school.length.w27": "14.41 英寸",
  "school.dev.w28": "宝宝的眼睛现在可以聚焦并追踪光线。宝宝现在可以区分不同的声音。",
  "school.fun.w28": "宝宝现在可以聚焦并追踪光线了！",
  "school.length.w28": "14.80 英寸",
  "school.dev.w29": "宝宝的骨骼已完全形成但仍较软。宝宝现在可以做出协调的动作。",
  "school.fun.w29": "宝宝现在可以做出协调的动作了！",
  "school.length.w29": "15.2 英寸",
  "school.dev.w30": "宝宝的大脑正在快速发育。宝宝现在可以学习并记住子宫外的声音。",
  "school.fun.w30": "宝宝现在可以学习并记住子宫外的声音了！",
  "school.length.w30": "15.71 英寸",
  "school.dev.w31": "宝宝的肺部几乎完全发育。宝宝现在可以练习呼吸动作。",
  "school.fun.w31": "宝宝现在可以练习呼吸动作了！",
  "school.length.w31": "16.18 英寸",
  "school.dev.w32": "宝宝的皮肤变得不那么透明了。宝宝现在可以做出面部表情。",
  "school.fun.w32": "宝宝现在可以做出面部表情了！",
  "school.length.w32": "16.69 英寸",
  "school.dev.w33": "宝宝的免疫系统正在增强。宝宝现在可以对您的触摸做出反应。",
  "school.fun.w33": "宝宝现在可以对您的触摸做出反应了！",
  "school.length.w33": "17.20 英寸",
  "school.dev.w34": "宝宝的肺部已完全发育。如果早产，宝宝现在可以自主呼吸。",
  "school.fun.w34": "如果早产，宝宝现在可以自主呼吸了！",
  "school.length.w34": "17.72 英寸",
  "school.dev.w35": "宝宝的大脑正在快速发育。宝宝现在可以学习并记住规律。",
  "school.fun.w35": "宝宝现在可以学习并记住规律了！",
  "school.length.w35": "18.19 英寸",
  "school.dev.w36": "宝宝的头部已进入分娩位置。宝宝现在可以做出协调的动作。",
  "school.fun.w36": "宝宝现在可以做出协调的动作了！",
  "school.length.w36": "18.66 英寸",
  "school.dev.w37": "宝宝已视为足月！在少量支持下，宝宝现在可以在子宫外存活。",
  "school.fun.w37": "宝宝已视为足月，可以在子宫外存活了！",
  "school.length.w37": "19.13 英寸",
  "school.dev.w38": "宝宝的大脑正在快速发育。宝宝现在可以学习并记住声音。",
  "school.fun.w38": "宝宝现在可以学习并记住声音了！",
  "school.length.w38": "19.61 英寸",
  "school.dev.w39": "宝宝的肺部已完全发育。宝宝现在可以自主呼吸。",
  "school.fun.w39": "宝宝现在可以自主呼吸了！",
  "school.length.w39": "19.96 英寸",
  "school.dev.w40": "宝宝准备出生了！在充分支持下，宝宝现在可以在子宫外存活。",
  "school.fun.w40": "宝宝准备出生了，可以在子宫外存活！",
  "school.length.w40": "20.16 英寸",
  "school.size.w4": "罂粟籽 🌱",
  "school.sizeDesc.w4": "小如罂粟籽",
  "school.size.w5": "芝麻 🌱",
  "school.sizeDesc.w5": "小如芝麻",
  "school.size.w6": "扁豆 🌱",
  "school.sizeDesc.w6": "一颗扁豆大小",
  "school.size.w7": "蓝莓 🫐",
  "school.sizeDesc.w7": "甜如蓝莓",
  "school.size.w8": "腰豆 🫘",
  "school.sizeDesc.w8": "形如腰豆",
  "school.size.w9": "葡萄 🍇",
  "school.sizeDesc.w9": "饱满如葡萄",
  "school.size.w10": "金桔 🍊",
  "school.sizeDesc.w10": "金桔大小",
  "school.size.w11": "无花果 🫒",
  "school.sizeDesc.w11": "无花果大小",
  "school.size.w12": "青柠 🍋",
  "school.sizeDesc.w12": "青柠大小",
  "school.size.w13": "桃子 🍑",
  "school.sizeDesc.w13": "软桃大小",
  "school.size.w14": "柠檬 🍋",
  "school.sizeDesc.w14": "柠檬大小",
  "school.size.w15": "苹果 🍎",
  "school.sizeDesc.w15": "脆苹果大小",
  "school.size.w16": "牛油果 🥑",
  "school.sizeDesc.w16": "牛油果大小",
  "school.size.w17": "梨 🍐",
  "school.sizeDesc.w17": "甜梨大小",
  "school.size.w18": "彩椒 🫑",
  "school.sizeDesc.w18": "彩椒大小",
  "school.size.w19": "芒果 🥭",
  "school.sizeDesc.w19": "芒果大小",
  "school.size.w20": "香蕉 🍌",
  "school.sizeDesc.w20": "香蕉长度",
  "school.size.w21": "胡萝卜 🥕",
  "school.sizeDesc.w21": "胡萝卜长度",
  "school.size.w22": "椰子 🥥",
  "school.sizeDesc.w22": "椰子大小",
  "school.size.w23": "葡萄柚 🍊",
  "school.sizeDesc.w23": "葡萄柚大小",
  "school.size.w24": "玉米 🌽",
  "school.sizeDesc.w24": "玉米棒长度",
  "school.size.w25": "花椰菜 🥦",
  "school.sizeDesc.w25": "花椰菜大小",
  "school.size.w26": "生菜 🥬",
  "school.sizeDesc.w26": "一颗生菜大小",
  "school.size.w27": "西兰花 🥦",
  "school.sizeDesc.w27": "西兰花大小",
  "school.size.w28": "茄子 🍆",
  "school.sizeDesc.w28": "茄子大小",
  "school.size.w29": "冬南瓜 🎃",
  "school.sizeDesc.w29": "南瓜大小",
  "school.size.w30": "卷心菜 🥬",
  "school.sizeDesc.w30": "卷心菜大小",
  "school.size.w31": "菠萝 🍍",
  "school.sizeDesc.w31": "菠萝大小",
  "school.size.w32": "南瓜 🎃",
  "school.sizeDesc.w32": "大南瓜",
  "school.size.w33": "蜜瓜 🍈",
  "school.sizeDesc.w33": "蜜瓜大小",
  "school.size.w34": "哈密瓜 🍈",
  "school.sizeDesc.w34": "哈密瓜大小",
  "school.size.w35": "白蜜瓜 🍈",
  "school.sizeDesc.w35": "白蜜瓜大小",
  "school.size.w36": "罗马生菜 🥬",
  "school.sizeDesc.w36": "罗马生菜大小",
  "school.size.w37": "瑞士甜菜 🥬",
  "school.sizeDesc.w37": "瑞士甜菜大小",
  "school.size.w38": "韭葱 🧅",
  "school.sizeDesc.w38": "韭葱长度",
  "school.size.w39": "小西瓜 🍉",
  "school.sizeDesc.w39": "小西瓜大小",
  "school.size.w40": "西瓜 🍉",
  "school.sizeDesc.w40": "完整西瓜大小"
};
