/** Terms of Service / User License Agreement for /terms (## = section heading, one paragraph per line). */
export const TERMS_OF_SERVICE = {
  en: {
    body: [
      'These Terms of Service ("Terms") govern your access to and use of the DoreHealth mobile application, website, and related services (the "Service") operated by DoreHealth ("we," "us," or "our"). By creating an account, signing in, or using the Service, you agree to these Terms and our Privacy Policy. If you do not agree, do not use the Service.',
      '## 1. Eligibility',
      'You must be at least 13 years old (or the minimum age required in your country) and able to enter a binding agreement. If you use the Service on behalf of an organization, you represent that you have authority to bind that organization.',
      '## 2. Your Account',
      'You are responsible for keeping your login credentials confidential and for all activity under your account. Provide accurate information and notify us promptly at support@dorehealth.app if you suspect unauthorized access.',
      '## 3. Permitted Use',
      "You may use the Service for personal, non-commercial wellness tracking and related features we provide. You agree not to: (a) violate applicable laws or third-party rights; (b) upload malware, spam, or harmful content; (c) attempt to reverse engineer, scrape, or disrupt the Service; (d) impersonate others or share another person's health data without permission; (e) use the Service to provide unauthorized medical advice or emergency services.",
      '## 4. Health and Medical Disclaimer',
      'DoreHealth provides educational and tracking tools only. The Service does not replace professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider for medical decisions. In an emergency, contact local emergency services immediately. Predictions and insights are estimates, not guarantees.',
      '## 5. Community and User Content',
      'If you post comments or other content, you grant us a limited license to host and display it as needed to operate the Service. You remain responsible for your content. We may remove content that violates these Terms or applicable law.',
      '## 6. Intellectual Property',
      'The Service, including software, design, trademarks, and content we provide, is owned by DoreHealth or its licensors and protected by intellectual property laws. These Terms do not grant you ownership—only a limited, revocable license to use the Service as intended.',
      '## 7. Privacy',
      'Our Privacy Policy explains how we collect and use personal data. By using the Service, you also agree to the Privacy Policy.',
      '## 8. Subscriptions and Payments',
      'Some features may require a paid subscription. Prices, billing cycles, and renewal terms are shown before purchase. Unless required by law or stated otherwise, fees are non-refundable once the billing period begins. You may cancel renewal through your app store account settings where applicable.',
      '## 9. Suspension and Termination',
      'You may stop using the Service and delete your account from Settings. We may suspend or terminate access if you materially breach these Terms, create risk to others, or where required by law. Provisions that by nature should survive (such as disclaimers and liability limits) remain in effect after termination.',
      '## 10. Disclaimers',
      'The Service is provided "as is" and "as available" to the fullest extent permitted by law. We do not warrant uninterrupted or error-free operation.',
      '## 11. Limitation of Liability',
      'To the maximum extent permitted by law, DoreHealth and its affiliates are not liable for indirect, incidental, special, consequential, or punitive damages, or for loss of data, profits, or goodwill arising from your use of the Service. Our total liability for any claim relating to the Service is limited to the greater of (a) amounts you paid us in the 12 months before the claim or (b) USD 100, except where such limits are prohibited by law.',
      '## 12. Governing Law and Disputes',
      'These Terms are governed by the laws applicable in your place of residence, except where mandatory consumer protection rules in your country require otherwise. Courts or authorities with jurisdiction over consumer disputes in your country may hear claims that cannot be resolved informally.',
      '## 13. Changes to These Terms',
      'We may update these Terms from time to time. We will post the updated version in the app and revise the "Last updated" date. Material changes may be communicated via in-app notice or email. Continued use after the effective date means you accept the updated Terms, unless your local law requires additional consent.',
      '## 14. Contact',
      'Questions about these Terms: support@dorehealth.app.',
    ].join('\n'),
  },
  zh: {
    body: [
      '本服务条款（「条款」）适用于您对 DoreHealth 移动应用、网站及相关服务（「服务」）的访问与使用。创建账户、登录或使用服务即表示您同意本条款及我们的隐私政策；如不同意，请勿使用服务。',
      '## 1. 资格',
      '您须年满 13 岁（或您所在国家/地区要求的最低年龄）并具备订立有约束力协议的能力。若代表组织使用服务，您声明有权使该组织受本条款约束。',
      '## 2. 您的账户',
      '您须对登录凭据保密并对账户下的一切活动负责。请提供准确信息；如怀疑未经授权的访问，请立即联系 support@dorehealth.app。',
      '## 3. 允许的使用',
      '您可将服务用于个人、非商业的健康追踪及相关功能。您同意不得：(a) 违反适用法律或第三方权利；(b) 上传恶意软件、垃圾信息或有害内容；(c) 试图逆向工程、抓取或干扰服务；(d) 冒充他人或未经同意分享他人健康数据；(e) 利用服务提供未经授权的医疗建议或紧急服务。',
      '## 4. 健康与医疗免责声明',
      'DoreHealth 仅提供教育与追踪工具，不能替代专业医疗建议、诊断或治疗。医疗决定请咨询合格医护人员。紧急情况请立即联系当地急救服务。预测与洞察仅为估算，不作保证。',
      '## 5. 社区与用户内容',
      '若您发布评论或其他内容，您授予我们为运营服务所需而托管和展示的有限许可。您仍对您的内容负责。我们可删除违反本条款或法律的内容。',
      '## 6. 知识产权',
      '服务（包括软件、设计、商标及我们提供的内容）归 DoreHealth 或其许可方所有，受知识产权法保护。本条款不授予所有权，仅授予按预期使用服务的有限、可撤销许可。',
      '## 7. 隐私',
      '我们的隐私政策说明如何收集和使用个人数据。使用服务即表示您亦同意隐私政策。',
      '## 8. 订阅与付款',
      '部分功能可能需要付费订阅。价格、计费周期及续订条款将在购买前展示。除法律要求或另有说明外，计费周期开始后费用不予退还。您可在适用的应用商店账户设置中取消续订。',
      '## 9. 暂停与终止',
      '您可随时停止使用服务并在设置中删除账户。若您严重违反本条款、对他人造成风险或法律要求，我们可暂停或终止访问。依性质应在终止后继续有效的条款（如免责声明与责任限制）仍然有效。',
      '## 10. 免责声明',
      '在法律允许的最大范围内，服务按「现状」和「可用性」提供。我们不保证服务不间断或无错误运行。',
      '## 11. 责任限制',
      '在法律允许的最大范围内，DoreHealth 及其关联方不对因使用服务而产生的间接、附带、特殊、后果性或惩罚性损害，或数据、利润或商誉损失承担责任。我们就与服务相关的任何索赔的总责任以 (a) 索赔前 12 个月内向我们支付的金额或 (b) 100 美元中较高者为准，法律禁止此类限制的情况除外。',
      '## 12. 适用法律与争议',
      '本条款受您居住地适用法律管辖，除非您所在国家的强制性消费者保护规则另有要求。无法非正式解决的消费者争议，可由您所在国家/地区有管辖权的法院或主管机关审理。',
      '## 13. 条款变更',
      '我们可能不时更新本条款，并在应用中发布更新版本及修订「最后更新」日期。重大变更可能通过应用内通知或电子邮件告知。在法律未要求额外同意的情况下，生效日后继续使用即表示接受更新后的条款。',
      '## 14. 联系我们',
      '有关本条款的问题：support@dorehealth.app。',
    ].join('\n'),
  },
  ms: {
    body: [
      'Terma Perkhidmatan ini ("Terma") mentadbir akses dan penggunaan anda terhadap aplikasi mudah alih, laman web, dan perkhidmatan berkaitan DoreHealth ("Perkhidmatan"). Dengan mencipta akaun, log masuk, atau menggunakan Perkhidmatan, anda bersetuju dengan Terma ini dan Dasar Privasi kami.',
      '## 1. Kelayakan',
      'Anda mesti berumur sekurang-kurangnya 13 tahun (atau umur minimum di negara anda) dan mampu membuat perjanjian yang mengikat.',
      '## 2. Akaun Anda',
      'Anda bertanggungjawab menjaga kerahsiaan kelayakan log masuk dan semua aktiviti di bawah akaun anda. Hubungi support@dorehealth.app jika anda mengesyaki akses tanpa kebenaran.',
      '## 3. Penggunaan Dibenarkan',
      'Anda boleh menggunakan Perkhidmatan untuk penjejakan kesejahteraan peribadi dan bukan komersial. Anda bersetuju untuk tidak melanggar undang-undang, mengganggu Perkhidmatan, atau menggunakan Perkhidmatan untuk nasihat perubatan tanpa kebenaran.',
      '## 4. Penafian Kesihatan',
      'DoreHealth hanya menyediakan alat pendidikan dan penjejakan. Perkhidmatan tidak menggantikan nasihat perubatan profesional. Rujuk penyedia penjagaan kesihatan yang layak untuk keputusan perubatan.',
      '## 5. Kandungan Pengguna',
      'Jika anda menyiarkan kandungan, anda memberi kami lesen terhad untuk mengehos dan memaparkannya. Kami boleh membuang kandungan yang melanggar Terma ini.',
      '## 6. Harta Intelek',
      'Perkhidmatan dilindungi undang-undang harta intelek. Terma ini memberi lesen terhad untuk menggunakan Perkhidmatan seperti dimaksudkan.',
      '## 7. Privasi',
      'Dasar Privasi kami menerangkan cara kami mengumpul dan menggunakan data peribadi.',
      '## 8. Langganan dan Bayaran',
      'Sesetengah ciri mungkin memerlukan langganan berbayar. Terma bil dan pembaharuan dipaparkan sebelum pembelian.',
      '## 9. Penggantungan dan Penamatan',
      'Anda boleh berhenti menggunakan Perkhidmatan dan memadam akaun dari Tetapan. Kami boleh menggantung akses jika anda melanggar Terma ini secara material.',
      '## 10. Penafian',
      'Perkhidmatan disediakan "sebagaimana adanya" setakat dibenarkan undang-undang.',
      '## 11. Had Liabiliti',
      'Setakat dibenarkan undang-undang, liabiliti kami terhad kepada jumlah yang dibayar oleh anda dalam 12 bulan sebelum tuntutan atau USD 100, yang mana lebih tinggi, kecuali jika undang-undang melarang had sedemikian.',
      '## 12. Undang-undang Tadbir dan Pertikaian',
      'Terma ini ditadbir oleh undang-undang yang terpakai di tempat tinggal anda, kecuali peraturan perlindungan pengguna mandatori memerlukan sebaliknya.',
      '## 13. Perubahan Terma',
      'Kami boleh mengemas kini Terma ini dan memaparkan versi terkini dalam aplikasi.',
      '## 14. Hubungi Kami',
      'Soalan tentang Terma ini: support@dorehealth.app.',
    ].join('\n'),
  },
  fa: {
    body: [
      'این «توافق‌نامه مجوز کاربر» و «شرایط استفاده از خدمات» («شرایط») دسترسی شما به اپلیکیشن، وب‌سایت و خدمات مرتبط دوره («خدمات») را تنظیم می‌کند. با ثبت‌نام، ورود یا استفاده از خدمات، این شرایط و «سیاست حفظ حریم خصوصی» ما را می‌پذیرید. در صورت عدم موافقت، از خدمات استفاده نکنید.',
      '## ۱. شرایط عمومی و پذیرش',
      'استفاده از خدمات منوط به رعایت قوانین و مقررات جمهوری اسلامی ایران از جمله قانون تجارت الکترونیک مصوب ۱۳۸۲، قانون جرایم رایانه‌ای مصوب ۱۳۸۸ و قانون حمایت از حقوق مصرف‌کنندگان مصوب ۱۳۸۸ است. ثبت‌نام یا ادامه استفاده، به‌منزله اعلام آگاهی و پذیرش این شرایط است.',
      '## ۲. صلاحیت و سن',
      'برای استفاده باید حداقل ۱۳ سال تمام داشته باشید (یا حداقل سن مقرر در کشور محل اقامت) و اهلیت قانونی انعقاد قرارداد را داشته باشید. والدین یا سرپرست قانونی مسئول استفاده زیر سن قانونی فرزندان هستند.',
      '## ۳. حساب کاربری',
      'مسئولیت حفظ محرمانگی اطلاعات ورود (ایمیل، رمز یک‌بارمصرف و غیره) و تمام فعالیت‌های انجام‌شده با حساب شما بر عهده خودتان است. اطلاعات ثبت‌نامی را دقیق و به‌روز نگه دارید. در صورت مشاهده دسترسی غیرمجاز، فوراً به support@دوره.app اطلاع دهید.',
      '## ۴. مجوز استفاده',
      'ما به شما مجوز محدود، غیرانحصاری، غیرقابل واگذاری و قابل فسخ برای استفاده شخصی و غیرتجاری از خدمات می‌دهیم. شما حق ندارید: (الف) قوانین ایران یا حقوق اشخاص ثالث را نقض کنید؛ (ب) بدافزار، هرزنامه یا محتوای مضر منتشر کنید؛ (ج) خدمات را مهندسی معکوس، استخراج داده یا مختل کنید؛ (د) هویت دیگران را جعل کنید یا بدون اجازه داده سلامت دیگران را ثبت کنید؛ (ه) از خدمات برای ارائه مشاوره پزشکی بدون مجوز یا خدمات اورژانسی استفاده کنید.',
      '## ۵. سلب مسئولیت پزشکی',
      'دوره ابزار آموزشی و ثبت اطلاعات سلامت است و جایگزین تشخیص، درمان یا مشاوره پزشکی حرفه‌ای نیست. برای تصمیم‌های پزشکی با پزشک یا مامای مجاز مشورت کنید. در اورژانس با ۱۱۵ یا اورژانس محلی تماس بگیرید. پیش‌بینی‌ها و بینش‌ها تخمینی هستند و تضمین دقیق بودن نمی‌شوند.',
      '## ۶. محتوای کاربر و انجمن',
      'در صورت انتشار نظر یا محتوا، مجوز محدودی برای میزبانی و نمایش آن در چارچوب ارائه خدمات به ما می‌دهید. مسئولیت محتوای منتشرشده با شماست. محتوای خلاف قانون، آیین‌نامه‌ها یا این شرایط قابل حذف است.',
      '## ۷. مالکیت فکری',
      'نرم‌افزار، طراحی، نشان تجاری و محتوای ارائه‌شده متعلق به دوره یا مجوزدهندگان است و تحت قوانین مالکیت فکری ایران و بین‌المللی محافظت می‌شود. این شرایط مالکیت را به شما منتقل نمی‌کند.',
      '## ۸. حریم خصوصی',
      'نحوه جمع‌آوری و استفاده از داده‌های شخصی در «سیاست حفظ حریم خصوصی» توضیح داده شده است. استفاده از خدمات به‌منزله پذیرش آن سیاست نیز هست.',
      '## ۹. اشتراک و پرداخت',
      'برخی امکانات ممکن است اشتراک پولی داشته باشند. قیمت، دوره صورتحساب و شرایط تمدید پیش از خرید نمایش داده می‌شود. مگر آنکه قانون حمایت از مصرف‌کننده یا سیاست فروشگاه برنامه خلاف آن باشد، پس از شروع دوره پرداخت، مبلغ مسترد نمی‌شود. لغو تمدید از تنظیمات حساب فروشگاه برنامه (کافه‌بازار، سیبچه، App Store و غیره) امکان‌پذیر است.',
      '## ۱۰. تعلیق و خاتمه',
      'می‌توانید هر زمان استفاده را متوقف و از تنظیمات درخواست حذف حساب دهید. در صورت نقض جدی شرایط، ایجاد خطر برای دیگران یا الزام قانونی، ممکن است دسترسی تعلیق یا قطع شود. بندهایی که ذاتاً پس از خاتمه معتبرند (مانند سلب مسئولیت) همچنان برقرار می‌مانند.',
      '## ۱۱. سلب ضمانت',
      'خدمات «همان‌گونه که هست» و «در دسترس بودن فعلی» ارائه می‌شود. تداوم بی‌وقفه یا عدم خطا تضمین نمی‌شود.',
      '## ۱۲. محدودیت مسئولیت',
      'در حداکثر گستره مجاز قانون، دوره در قبال خسارات غیرمستقیم، تبعی، خاص یا از دست رفتن داده یا سود مسئول نیست. سقف مسئولیت ما برای هر ادعا مرتبط با خدمات، بیشتر از (الف) مبالغ پرداختی شما در ۱۲ ماه قبل از ادعا یا (ب) معادل ۱۰۰ دلار آمریکا نیست، مگر آنکه قانون ایران چنین محدودیتی را ممنوع کند.',
      '## ۱۳. قانون حاکم و حل اختلاف',
      'این شرایط تابع قوانین جمهوری اسلامی ایران است. اختلافات ابتدا از طریق مذاکره و پشتیبانی (support@دوره.app) پیگیری می‌شود. در صورت عدم حصول توافق، مراجع قضایی صالح در ایران صالح به رسیدگی هستند. حقوق مصرف‌کننده طبق قانون حمایت از حقوق مصرف‌کنندگان برای شما محفوظ است.',
      '## ۱۴. تغییر شرایط',
      'ممکن است این شرایط به‌روزرسانی شود. نسخه جدید در برنامه با تاریخ «آخرین به‌روزرسانی» منتشر می‌شود. تغییرات مهم از طریق اعلان درون‌برنامه یا ایمیل اطلاع داده می‌شود. استفاده پس از تاریخ اجرا به‌منزله پذیرش نسخه جدید است، مگر قانون رضایت مجدد بخواهد.',
      '## ۱۵. تماس با ما',
      'پرسش درباره این شرایط: support@دوره.app',
    ].join('\n'),
  },
} as const;
